Fix for DIRSERVER-1249 (rc.d init script doesn't work for Mandriva Linux : location of "id" binary).
git-svn-id: https://svn.apache.org/repos/asf/directory/daemon/trunk@694199 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/plugin/src/main/resources/org/apache/directory/daemon/installers/solarispkg/apacheds-init b/plugin/src/main/resources/org/apache/directory/daemon/installers/solarispkg/apacheds-init
--- a/plugin/src/main/resources/org/apache/directory/daemon/installers/solarispkg/apacheds-init
+++ b/plugin/src/main/resources/org/apache/directory/daemon/installers/solarispkg/apacheds-init
@@ -310,9 +310,13 @@ checkUser() {
             IDEXE="/usr/bin/id"
             if [ ! -x "$IDEXE" ]
             then
-                echo "Unable to locate 'id'."
-                echo "Please report this message along with the location of the command on your system."
-                exit 1
+                IDEXE="/bin/id"
+                if [ ! -x "$IDEXE" ]
+                then
+                    echo "Unable to locate 'id'."
+                    echo "Please report this message along with the location of the command on your system."
+                    exit 1
+                fi
             fi
         fi
 
